language: node_js
sudo: required
node_js:
  - 10
  - 8
  - 6
before_install:
  - sudo sysctl fs.inotify.max_user_watches=524288
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install: 'yarn install --ignore-engines'
script:
  # Test source
  - yarn flow
  - yarn lint
  - yarn test --maxWorkers=2 --coverage
after_success:
  # Report coverage
  - yarn codecov
cache:
  yarn: true
